name: Handbook
version: '1.0-SNAPSHOT'
main: org.mellurboo.handbook.Handbook
api-version: '1.21'

commands:
  handbook:
    description: Open the handbook for your viewing pleasure
    usage: /handbook [give]

permissions:
  handbook.admin:
    default: false